services:
  apache:
    build:
      context: .
    container_name: ${APP_NAME}-apache
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://${APP_NAME}:${DATABASE_PASSWORD}@mysql:3306/${APP_NAME}_prod?serverVersion=10.6"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls=true"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    volumes:
      - hpln-uploads:/var/www/html/public/uploads

volumes:
  hpln-uploads:


networks:
  web:
    external: true
